/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv` (hash: 022a4264dff96d4459174c49873ee928)
interface __BaseEnv_CloudflareEnv {
	ATTACHMENTS: R2Bucket;
	HYPERDRIVE: Hyperdrive;
	JOBS_QUEUE: Queue;
	ASSETS: Fetcher;
	RESEND_API_KEY: string;
	RESEND_WEBHOOK_SECRET: string;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	BETTER_AUTH_URL: string;
	NEXT_PUBLIC_APP_URL: string;
	DATABASE_URL: string;
	TELNYX_STATUS: string;
	TELNYX_API_KEY: string;
	BETTER_AUTH_SECRET: string;
	EMAIL_DOMAIN: string;
	AUTH_EMAIL_FROM: string;
	TELNYX_PUBLIC_KEY: string;
	TELNYX_MESSAGING_PROFILE_ID: string;
	CUSTOM_WEBHOOK_ENCRYPTION_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "RESEND_API_KEY" | "RESEND_WEBHOOK_SECRET" | "GOOGLE_CLIENT_ID" | "GOOGLE_CLIENT_SECRET" | "BETTER_AUTH_URL" | "NEXT_PUBLIC_APP_URL" | "DATABASE_URL" | "TELNYX_STATUS" | "TELNYX_API_KEY" | "BETTER_AUTH_SECRET" | "EMAIL_DOMAIN" | "AUTH_EMAIL_FROM" | "TELNYX_PUBLIC_KEY" | "TELNYX_MESSAGING_PROFILE_ID" | "CUSTOM_WEBHOOK_ENCRYPTION_KEY">> {}
}
