/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=JobsEnv` (hash: fbab5d0ac36ad40144540a46807585bf)
interface __BaseEnv_JobsEnv {
	ATTACHMENTS: R2Bucket;
	HYPERDRIVE: Hyperdrive;
	TELNYX_STATUS: "active";
	WEBHOOK_TRANSPORT: "disabled";
	BILLING_ENABLED: "false";
	RESEND_API_KEY: string;
	TELNYX_API_KEY: string;
	CUSTOM_WEBHOOK_ENCRYPTION_KEY: string;
	STRIPE_SECRET_KEY: string;
	TELNYX_PUBLIC_KEY: string;
	TELNYX_MESSAGING_PROFILE_ID: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_JobsEnv {}
}
interface JobsEnv extends __BaseEnv_JobsEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
}
