/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=JobsEnv` (hash: b2bf28daf79d85863fef468e57ed61e3)
interface __BaseEnv_JobsEnv {
	ATTACHMENTS: R2Bucket;
	HYPERDRIVE: Hyperdrive;
	TELNYX_STATUS: "active";
	WEBHOOK_TRANSPORT: "disabled";
	BILLING_ENABLED: "false";
	RESEND_API_KEY: string;
	TELNYX_API_KEY: string;
	CUSTOM_WEBHOOK_ENCRYPTION_KEY: string;
	STRIPE_SECRET_KEY: string;
	TELNYX_PUBLIC_KEY: string;
	TELNYX_MESSAGING_PROFILE_ID: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_JobsEnv {}
}
interface JobsEnv extends __BaseEnv_JobsEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TELNYX_STATUS" | "WEBHOOK_TRANSPORT" | "BILLING_ENABLED" | "RESEND_API_KEY" | "TELNYX_API_KEY" | "CUSTOM_WEBHOOK_ENCRYPTION_KEY" | "STRIPE_SECRET_KEY" | "TELNYX_PUBLIC_KEY" | "TELNYX_MESSAGING_PROFILE_ID">> {}
}
