/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=JobsEnv` (hash: 470afef75d7cc7bb3312ac6f2ecabc4c)
interface __BaseEnv_JobsEnv {
	ATTACHMENTS: R2Bucket;
	HYPERDRIVE: Hyperdrive;
	TELNYX_STATUS: "active";
	WEBHOOK_TRANSPORT: "disabled";
	RESEND_API_KEY: string;
	TELNYX_API_KEY: string;
	CUSTOM_WEBHOOK_ENCRYPTION_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_JobsEnv {}
}
interface JobsEnv extends __BaseEnv_JobsEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TELNYX_STATUS" | "WEBHOOK_TRANSPORT" | "RESEND_API_KEY" | "TELNYX_API_KEY" | "CUSTOM_WEBHOOK_ENCRYPTION_KEY">> {}
}
